### ISSUE TITLE
.py改写成shell script

### ISSUE THREAD

**Issue by dmyang42** [topologyYDM/speed_test#11]
其实讲道理不该有任何python文件

最后等基本都完成后按照python来改写成shell script

**Comment by dmyang42** [comment]
:heart: :monkey_face: :see_no_evil: :octocat:

**Comment by ppzqh** [comment]
你太强了 我逛hupu

**Comment by dmyang42** [comment]
目前origin / shell分支里把v0.3功能都改成了shell script，作为v0.4

**Comment by dmyang42** [comment]
主要部分就算现在shell branch。然后处理啥的再讨论
