### ISSUE TITLE
批量处理

### ISSUE THREAD

**Issue by dmyang42** [topologyYDM/speed_test#3]
多个节点多个配置的json文件，一键处理需要写一写

**Comment by ppzqh** [comment]
I will work on this one.
But I am not sure if those config files exported from shadowsocks can be used in `sslocal -c ./config`

**current config:**
`{
  "protocol_param" : "",
  "method" : "rc4-md5",
  "protocol" : "origin",
  "server" : "cn2.darkcloud.link",
  "password" : "WtyKghNCwPYW",
  "local_address" : "127.0.0.1",
  "server_port" : 12565,
  "timeout" : 60,
  "local_port" : 1086,
  "obfs_param" : "",
  "obfs" : "plain"
}
`

**example of exported config:**
`
    {
      "enable" : true,
      "password" : "WtyKghNCwPYW",
      "method" : "rc4-md5",
      "remarks" : "",
      "server" : "cn2.darkcloud.link",
      "obfs" : "plain",
      "protocol" : "origin",
      "server_port" : 12565,
      "remarks_base64" : ""
    }
`

**Comment by dmyang42** [comment]
你export出的可以先写个python脚本转换一下，包括文件名也要处理下

以后爬下来的可能可以直接到我们想要的，因为只要模拟登陆了，html代码里有各种tag，处理起来就跟json一样方便

**Comment by dmyang42** [comment]
我觉得可能直接就可以用，毕竟该有的key都有了。你可以先试试 :hamster:

**Comment by ppzqh** [comment]
ok

**Comment by dmyang42** [comment]
你设计好方法后跟我说下，输出处理也要对应。
因为最后要比较，我觉得这样比较合理：
从网上down下来若干个.json，这里面有他们的IP，然后.sh脚本跑每一个，最后把IP(或者一个与IP对应的序号，比如1.json的文件名，总之要能知道是哪个)和速度结果写进一个out文件里，然后我来写处理的.py把out处理好

**Comment by ppzqh** [comment]
**instruction:**
还不知道

**input file:**
`
{"enable": true, "protocol": "origin", "server_port": 12565, "remarks_base64": "", "server": "******", "obfs": "plain", "remarks": "", "password": "*****", "method": "rc4-md5"}
`

**output file:**
Server: "****"
Ping: 10.813 ms
Download: 8.70 Mbit/s
Upload: 8.32 Mbit/s

**Comment by dmyang42** [comment]
基本上解决了。一些修改的在v1.0提交之后再提出issue
