### ISSUE TITLE
chacha20-ietf支持

### ISSUE THREAD

**Issue by dmyang42** [topologyYDM/speed_test#6]
现在chacha20-ietf还不支持，要本地配置下ss
配置好测试成功后关闭这个issue

**Comment by topologyYDM** [comment]
有点困难

网上第一类教程说装一个东西就可以了 我装好后好像sslocal还是不允许chacha20-ietf

另外可以用ss-local 但我用ss-local连hkt4上不了网 但这个节点是ok的

**Comment by topologyYDM** [comment]
我错了 ss更新到3.0就支持chacha20-ietf了

**Comment by dmyang42** [comment]
1：使用ss
    Update Shadowsocks to v3.0
    在Cordcloud中关闭混淆那些，即cordcloud中可以看到节点支持shadowsocks
    config文件的标准格式在新的branch中给出
2：使用ssr
    应该可以连原来那些节点，但要在 @ppzqh 你电脑上看终端跑ssr，我这里再装ssr比较麻烦
