### ISSUE TITLE
连接失败后的错误信息及处理

### ISSUE THREAD

**Issue by dmyang42** [topologyYDM/speed_test#8]
连接失败后，不应该再测速，同时因为没有sslocal的进程，也不用去kill

**Comment by ppzqh** [comment]
之后的程序中加一条判断语句
💩有没有表情列表的

**Comment by topologyYDM** [comment]
有 :sun_with_face:

**Comment by ppzqh** [comment]
ok:kissing_heart:

**Comment by dmyang42** [comment]
两类错误：
1. 节点信息错误（导出的话不太可能）
2. 节点是臭的

在`sslocal -c ***.json -q &; export ALL_PROXY=socks5://127.0.0.1:1080`后进行:
`curl --connect-timeout 5 -m 6 -i "baidu.com"`
若返回HTTP开头的结果，则成功，继续进行测速
若是1类错误，curl给出(56)错误
若是2类错误，curl给出(28)错误

这是我的思路来改这个，你们如果有啥其他思路在这个issue下给我留言 @ppzqh @FrendoWu

**Comment by dmyang42** [comment]
on current origin / shell branch v0.5
